"""
Build a backend-disclosure manifest from all R-run results.

For each R-experiment that has a results directory, walks the latest
run's `config_snapshot.json` and extracts:
    - backend.kind                  ("mock" | "hf_local" | "hf_inference")
    - backend.model_name            (e.g. "Qwen/Qwen2.5-7B-Instruct")
    - dataset.name + split + n_examples
    - seeds used
    - run timestamp
    - git SHA at run time (if recorded)

Writes:
    artifacts/backends_manifest.json     (machine-readable)
    artifacts/backends_manifest.md       (renders in GitHub README)
    artifacts/backends_manifest.tex      (drops into the paper appendix)

The manifest is the single source of truth that makes the experimental
section reproducible — reviewers can see at a glance which model
produced which figure, on which dataset, with how many examples.

Usage:
    python scripts/build_backends_manifest.py
    # or, with explicit paths:
    python scripts/build_backends_manifest.py --results-dir results/ --out-dir artifacts/
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
sys.path.insert(0, str(Path(__file__).resolve().parents[0]))

from _common import log_info, log_section


# --------------------------------------------------------------------------
# Walk results/ to find the latest run per experiment
# --------------------------------------------------------------------------

EXPERIMENTS = ("r1", "r2", "r3", "r4", "r5")


def _latest_run(results_root: Path, prefix: str) -> Path | None:
    """Return the most recent run directory matching `<prefix>*`."""
    if not results_root.exists():
        return None
    candidates = sorted(
        [p for p in results_root.glob(f"{prefix}*") if p.is_dir()],
        key=lambda p: p.stat().st_mtime,
    )
    return candidates[-1] if candidates else None


def _read_snapshot(run_dir: Path) -> dict | None:
    snap = run_dir / "config_snapshot.json"
    if not snap.exists():
        return None
    try:
        return json.loads(snap.read_text())
    except json.JSONDecodeError:
        return None


def _summarize_run(run_dir: Path, snap: dict) -> dict:
    """Pull the disclosure-relevant fields out of a config snapshot."""
    backend = snap.get("backend", {}) or {}
    dataset = snap.get("dataset", {}) or {}

    # Try to read the result JSON's `seeds` field too (the run script
    # may have mutated it from CLI overrides)
    seeds = []
    for f in run_dir.glob("*.json"):
        if f.name == "config_snapshot.json":
            continue
        try:
            d = json.loads(f.read_text())
            if isinstance(d, dict) and "seeds" in d:
                seeds = d["seeds"]
                break
        except json.JSONDecodeError:
            continue

    # Run timestamp from directory mtime (good enough for disclosure)
    ts = datetime.fromtimestamp(
        run_dir.stat().st_mtime, tz=timezone.utc
    ).isoformat()

    return {
        "run_dir": str(run_dir.name),
        "backend_kind": backend.get("kind", "unknown"),
        "model_name": backend.get("model_name") or "(none — mock backend)",
        "dataset_name": dataset.get("name", "unknown"),
        "dataset_split": dataset.get("split", "—"),
        "n_examples": dataset.get("n_examples", "—"),
        "seeds": seeds,
        "timestamp_utc": ts,
        "git_sha": snap.get("_git_sha", "unknown"),
    }


# --------------------------------------------------------------------------
# Renderers
# --------------------------------------------------------------------------

_HUMAN_BACKEND = {
    "mock": "🟡 mock (deterministic, no LLM)",
    "hf_local": "🟢 HF local (model loaded on-device)",
    "hf_inference": "🟢 HF Inference API (remote)",
    "unknown": "⚪ unknown",
}


def render_markdown(records: dict[str, dict]) -> str:
    lines = [
        "# Backend disclosure manifest",
        "",
        "_Auto-generated by `scripts/build_backends_manifest.py`._",
        "",
        "Each experiment in this paper was run with the LLM backend below.",
        "Mock-backend rows are watermarked in the corresponding figures.",
        "",
        "| Experiment | Backend kind | Model | Dataset | Examples | Seeds | Run UTC |",
        "|---|---|---|---|---|---|---|",
    ]
    for r_id in EXPERIMENTS:
        rec = records.get(r_id)
        if rec is None:
            lines.append(
                f"| **{r_id.upper()}** | — | _no run found_ | — | — | — | — |"
            )
            continue
        seeds_str = (
            ",".join(str(s) for s in rec["seeds"])
            if rec["seeds"] else "—"
        )
        backend_label = _HUMAN_BACKEND.get(
            rec["backend_kind"], rec["backend_kind"]
        )
        lines.append(
            f"| **{r_id.upper()}** "
            f"| {backend_label} "
            f"| `{rec['model_name']}` "
            f"| {rec['dataset_name']} ({rec['dataset_split']}) "
            f"| {rec['n_examples']} "
            f"| {seeds_str} "
            f"| {rec['timestamp_utc'][:19]} |"
        )
    lines.extend([
        "",
        "## What the backend kinds mean",
        "",
        "- **mock**: deterministic stand-in. Useful for CI, smoke tests, "
        "and end-to-end pipeline verification on a laptop. Figures from "
        "mock runs ship with a diagonal `MOCK BACKEND · PREVIEW ONLY` watermark.",
        "- **hf_local**: the model is loaded on-device via Transformers. "
        "Reproducible bit-for-bit given the same revision tag.",
        "- **hf_inference**: the model is called via HF Inference API. "
        "Reproducible up to the provider's deployment of the model "
        "revision; we record the model id and call timestamp.",
        "",
    ])
    return "\n".join(lines)


def render_latex(records: dict[str, dict]) -> str:
    """Tabular for the paper appendix — drop into a .tex file."""
    lines = [
        "% Auto-generated by scripts/build_backends_manifest.py",
        "\\begin{table}[h]",
        "\\centering",
        "\\small",
        "\\caption{Backend disclosure for the experiments in this paper. "
        "Mock-backend runs are clearly marked with a watermark in the "
        "corresponding figures.}",
        "\\label{tab:backends}",
        "\\begin{tabular}{llllll}",
        "\\toprule",
        "Exp & Backend & Model & Dataset & N & Seeds \\\\",
        "\\midrule",
    ]
    for r_id in EXPERIMENTS:
        rec = records.get(r_id)
        if rec is None:
            lines.append(
                f"{r_id.upper()} & --- & \\textit{{no run}} & --- & --- & --- \\\\"
            )
            continue
        # Escape underscores for LaTeX
        def _esc(s: object) -> str:
            return str(s).replace("_", r"\_")
        seeds_str = (
            ",".join(str(s) for s in rec["seeds"])
            if rec["seeds"] else "---"
        )
        lines.append(
            f"{r_id.upper()} & "
            f"{_esc(rec['backend_kind'])} & "
            f"\\texttt{{{_esc(rec['model_name'])}}} & "
            f"{_esc(rec['dataset_name'])} & "
            f"{rec['n_examples']} & "
            f"{seeds_str} \\\\"
        )
    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ])
    return "\n".join(lines)


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def main(
    results_dir: str = "results",
    out_dir: str = "artifacts",
) -> int:
    log_section("Building backend manifest")
    results_root = Path(results_dir)
    out_root = Path(out_dir)
    out_root.mkdir(parents=True, exist_ok=True)

    records: dict[str, dict] = {}
    for r_id in EXPERIMENTS:
        run_dir = _latest_run(results_root, r_id)
        if run_dir is None:
            log_info(f"  {r_id}: no run dir found under {results_root}")
            continue
        snap = _read_snapshot(run_dir)
        if snap is None:
            log_info(f"  {r_id}: {run_dir.name} has no config_snapshot.json")
            continue
        rec = _summarize_run(run_dir, snap)
        records[r_id] = rec
        log_info(
            f"  {r_id}: {rec['backend_kind']} · {rec['model_name']} · "
            f"{rec['dataset_name']} · n={rec['n_examples']}"
        )

    if not records:
        log_info("No runs found. Run `make smoke-full` first.")
        return 1

    # Emit all three formats
    json_path = out_root / "backends_manifest.json"
    md_path = out_root / "backends_manifest.md"
    tex_path = out_root / "backends_manifest.tex"

    json_path.write_text(
        json.dumps({
            "generated_utc": datetime.now(timezone.utc).isoformat(),
            "experiments": records,
        }, indent=2)
    )
    md_path.write_text(render_markdown(records))
    tex_path.write_text(render_latex(records))

    log_info(f"  -> {json_path}")
    log_info(f"  -> {md_path}")
    log_info(f"  -> {tex_path}")
    return 0


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--results-dir", default="results")
    p.add_argument("--out-dir", default="artifacts")
    args = p.parse_args()
    sys.exit(main(results_dir=args.results_dir, out_dir=args.out_dir))
