"""
scripts/make_tables.py

Regenerates LaTeX-ready tables from saved experiment JSONs. Each table is
written as a self-contained .tex file using booktabs + siunitx + threeparttable.

To use in the paper:

    \\begin{table}[t]
      \\input{tables/t1_audit_decomposition.tex}
    \\end{table}

The tables we emit:
    T1  audit-decomposition channels with Wilson CIs       (Theorem 1)
    T2  redundancy law: empirical vs theory plug-in vs UCB (Theorem 2)
    T3  responsibility identification per corruption regime (Theorem 3 part i)
    T4  risk policy cost/harm per epsilon                  (Theorem 3 part ii)
    T5  overhead per (backend, config)                     (R5 / ICML W2)

Like make_figures.py, this NEVER reruns experiments — only reads results/.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
sys.path.insert(0, str(Path(__file__).resolve().parents[0]))

from _common import log_info, log_section, project_root


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _latest_run(results_dir: Path, rid: str) -> Path | None:
    base = results_dir / rid
    if not base.exists():
        return None
    candidates = sorted([p for p in base.iterdir() if p.is_dir()],
                         key=lambda p: p.stat().st_mtime, reverse=True)
    for c in candidates:
        if (c / f"{rid}.json").exists():
            return c
    return None


def _load(p: Path) -> dict[str, Any]:
    with p.open("r") as fh:
        return json.load(fh)


def _fmt_num(x: float, digits: int = 4) -> str:
    """Format a float for LaTeX siunitx \\num{} input."""
    if x is None:
        return r"\textemdash"
    if isinstance(x, str):
        return x
    if abs(x) < 1e-4 and x != 0.0:
        return f"{x:.2e}"
    return f"{x:.{digits}f}"


def _fmt_ci(lo: float, hi: float, digits: int = 4) -> str:
    return f"[{_fmt_num(lo, digits)}, {_fmt_num(hi, digits)}]"


# ---------------------------------------------------------------------------
# T1 — Audit decomposition (Theorem 1)
# ---------------------------------------------------------------------------


_T1_TEMPLATE = r"""% Auto-generated by scripts/make_tables.py — do not edit.
\begin{threeparttable}
  \centering
  \caption{Audit decomposition (Theorem~\ref{thm:safety}). Empirical estimates
    and 95\% bootstrap CIs across $S$ seeds for each channel and the union
    bound. By construction, $\Pr(\text{accept \& wrong}) \le
    \Pr(\IntFail) + \Pr(\ReplayFail) + \Pr(\CheckFail) + \Pr(\CovGap)$.}
  \label{tab:r1-audit}
  \begin{tabular}{l S[table-format=1.4] l}
    \toprule
    \textbf{Quantity} & {\textbf{Mean}} & \textbf{95\% CI} \\
    \midrule
%ROWS%
    \bottomrule
  \end{tabular}
  \begin{tablenotes}\footnotesize
    \item Source: \texttt{%SOURCE%}.
  \end{tablenotes}
\end{threeparttable}
"""


def write_t1_audit_decomposition(run_dir: Path, out: Path) -> None:
    data = _load(run_dir / "r1.json")
    agg = data["aggregated"]
    rows = []
    pretty = {
        "lhs_accept_and_wrong": r"$\Pr(\text{accept \& wrong})$ \emph{(LHS)}",
        "p_int_fail": r"$\Pr(\IntFail)$",
        "p_replay_fail": r"$\Pr(\ReplayFail)$",
        "p_check_fail": r"$\Pr(\CheckFail)$",
        "p_cov_gap": r"$\Pr(\CovGap)$",
        "rhs_union": r"\emph{Union (RHS)}",
    }
    for k, label in pretty.items():
        m = agg[k]["mean"]
        lo, hi = agg[k]["ci"]
        rows.append(f"    {label} & {_fmt_num(m)} & {_fmt_ci(lo, hi)} \\\\")
    body = _T1_TEMPLATE.replace("%ROWS%", "\n".join(rows))
    body = body.replace("%SOURCE%", str(run_dir / "r1.json").replace("_", r"\_"))
    out.write_text(body)


# ---------------------------------------------------------------------------
# T2 — Redundancy law (Theorem 2)
# ---------------------------------------------------------------------------


_T2_TEMPLATE = r"""% Auto-generated by scripts/make_tables.py — do not edit.
\begin{threeparttable}
  \centering
  \caption{Redundancy law (Theorem~\ref{thm:redundancy}). Empirical
    false-accept rate $\Pr(A_t^{(k,k)} \cap \text{wrong})$ vs. the theoretical
    bound $\rho^{k-1}\eps^k$ at multiple redundancy levels $k$. Both
    plug-in and UCB versions of $\rho$ are reported.}
  \label{tab:r2-redundancy}
  \begin{tabular}{S[table-format=2.0] S[table-format=1.5] l S[table-format=2.4] S[table-format=2.4] S[table-format=2.4] S[table-format=2.4]}
    \toprule
    {$k$} & {Empirical} & {95\% CI} & {Theory plug-in} & {Theory UCB} & {$\hat\rho$} & {$\rho_{\mathrm{UCB}}$} \\
    \midrule
%ROWS%
    \bottomrule
  \end{tabular}
  \begin{tablenotes}\footnotesize
    \item Source: \texttt{%SOURCE%}.
  \end{tablenotes}
\end{threeparttable}
"""


def write_t2_redundancy(run_dir: Path, out: Path) -> None:
    data = _load(run_dir / "r2.json")
    rows = []
    for entry in data["aggregated_per_k"]:
        k = entry["k"]
        emp = entry["empirical_mean"]
        lo, hi = entry["empirical_ci"]
        tpi = entry["theory_plug_in_mean"]
        tub = entry["theory_ucb_max"]
        rho_hat = entry["rho_hat_mean"]
        rho_ucb = entry["rho_ucb_max"]
        rows.append(
            f"    {k} & {_fmt_num(emp, 5)} & {_fmt_ci(lo, hi, 5)} & "
            f"{_fmt_num(tpi)} & {_fmt_num(tub)} & "
            f"{_fmt_num(rho_hat)} & {_fmt_num(rho_ucb)} \\\\"
        )
    body = _T2_TEMPLATE.replace("%ROWS%", "\n".join(rows))
    body = body.replace("%SOURCE%", str(run_dir / "r2.json").replace("_", r"\_"))
    out.write_text(body)


# ---------------------------------------------------------------------------
# T3 — Responsibility identification per corruption regime
# ---------------------------------------------------------------------------


_T3_TEMPLATE = r"""% Auto-generated by scripts/make_tables.py — do not edit.
\begin{threeparttable}
  \centering
  \caption{Top-1 root-cause identification accuracy under controlled
    corruption (Theorem~\ref{thm:operational} part i). For each regime we
    report the fraction of examples where the highest-$\Resp$ component
    matches the injected target, with bootstrap 95\% CIs.}
  \label{tab:r3-responsibility}
  \begin{tabular}{l S[table-format=1.4] l c}
    \toprule
    \textbf{Regime} & {\textbf{Top-1 acc.}} & \textbf{95\% CI} & \textbf{Median rank-recovery prob.} \\
    \midrule
%ROWS%
    \bottomrule
  \end{tabular}
  \begin{tablenotes}\footnotesize
    \item Source: \texttt{%SOURCE%}.
  \end{tablenotes}
\end{threeparttable}
"""


def write_t3_responsibility(run_dir: Path, out: Path) -> None:
    data = _load(run_dir / "r3.json")
    agg = data["aggregated"]
    # Pull median rank recovery from per-seed
    median_rrp_per_regime: dict[str, list[float]] = {}
    for s in data["per_seed"]:
        for r in s["per_regime"]:
            median_rrp_per_regime.setdefault(r["regime"], []).append(r["median_rank_recovery_prob"])
    rows = []
    for name, val in agg.items():
        m = val.get("top1_accuracy_mean")
        ci = val.get("ci", [None, None])
        rrp_list = median_rrp_per_regime.get(name, [])
        rrp = sum(rrp_list) / len(rrp_list) if rrp_list else 0.0
        m_str = _fmt_num(m) if m is not None else r"\textemdash"
        ci_str = _fmt_ci(ci[0], ci[1]) if ci[0] is not None else r"\textemdash"
        rows.append(f"    \\texttt{{{name}}} & {m_str} & {ci_str} & {_fmt_num(rrp)} \\\\")
    body = _T3_TEMPLATE.replace("%ROWS%", "\n".join(rows))
    body = body.replace("%SOURCE%", str(run_dir / "r3.json").replace("_", r"\_"))
    out.write_text(body)


# ---------------------------------------------------------------------------
# T4 — Risk policy cost / harm per epsilon
# ---------------------------------------------------------------------------


_T4_TEMPLATE = r"""% Auto-generated by scripts/make_tables.py — do not edit.
\begin{threeparttable}
  \centering
  \caption{Risk-aware control under privacy budgets $\eps$. Cost and harm
    are reported per claim, averaged over seeds with bootstrap 95\% CIs.
    $\eps = \infty$ corresponds to the no-DP utility upper bound. The
    threshold-PCG policy implements Theorem~\ref{thm:operational} part ii.}
  \label{tab:r4-risk-privacy}
  \begin{tabular}{l l S[table-format=1.4] l S[table-format=1.4] l}
    \toprule
    \textbf{$\eps$} & \textbf{Policy} & {\textbf{Cost/claim}} & \textbf{Cost CI} & {\textbf{Harm/claim}} & \textbf{Harm CI} \\
    \midrule
%ROWS%
    \bottomrule
  \end{tabular}
  \begin{tablenotes}\footnotesize
    \item Source: \texttt{%SOURCE%}.
  \end{tablenotes}
\end{threeparttable}
"""


def write_t4_risk_privacy(run_dir: Path, out: Path) -> None:
    data = _load(run_dir / "r4.json")
    agg = data["aggregated"]
    rows = []
    for eps_key in agg:
        for pname in ["always_answer", "threshold_pcg", "learned"]:
            if pname not in agg[eps_key]:
                continue
            entry = agg[eps_key][pname]
            cm = entry["cost_mean"]
            cci = entry["cost_ci"]
            hm = entry["harm_mean"]
            hci = entry["harm_ci"]
            rows.append(
                f"    {eps_key} & \\texttt{{{pname}}} & "
                f"{_fmt_num(cm)} & {_fmt_ci(cci[0], cci[1])} & "
                f"{_fmt_num(hm)} & {_fmt_ci(hci[0], hci[1])} \\\\"
            )
    body = _T4_TEMPLATE.replace("%ROWS%", "\n".join(rows))
    body = body.replace("%SOURCE%", str(run_dir / "r4.json").replace("_", r"\_"))
    out.write_text(body)


# ---------------------------------------------------------------------------
# T5 — Overhead per (backend, config)
# ---------------------------------------------------------------------------


_T5_TEMPLATE = r"""% Auto-generated by scripts/make_tables.py — do not edit.
\begin{threeparttable}
  \centering
  \caption{Token and time overhead per claim under different backends and
    PCG configurations. Reported values are means across seeds with
    bootstrap 95\% CIs. Directly answers reviewer concerns about
    multi-agent token/latency cost.}
  \label{tab:r5-overhead}
  \begin{tabular}{l l S[table-format=4.1] l S[table-format=4.0] l}
    \toprule
    \textbf{Backend} & \textbf{Config} & {\textbf{Wall (ms)}} & \textbf{Wall CI} & {\textbf{Tokens}} & \textbf{Tokens CI} \\
    \midrule
%ROWS%
    \bottomrule
  \end{tabular}
  \begin{tablenotes}\footnotesize
    \item Source: \texttt{%SOURCE%}.
  \end{tablenotes}
\end{threeparttable}
"""


def write_t5_overhead(run_dir: Path, out: Path) -> None:
    data = _load(run_dir / "r5.json")
    rows = []
    for entry in data["aggregated"]:
        bnd = entry["backend"].replace("_", r"\_")
        conf = entry["config"].replace("_", r"\_")
        wm = entry["wall_ms_per_claim_mean"]
        wci = entry["wall_ms_per_claim_ci"]
        tm = entry["tokens_per_claim_mean"]
        tci = entry["tokens_per_claim_ci"]
        rows.append(
            f"    \\texttt{{{bnd}}} & \\texttt{{{conf}}} & "
            f"{_fmt_num(wm, 1)} & {_fmt_ci(wci[0], wci[1], 1)} & "
            f"{_fmt_num(tm, 0)} & {_fmt_ci(tci[0], tci[1], 0)} \\\\"
        )
    body = _T5_TEMPLATE.replace("%ROWS%", "\n".join(rows))
    body = body.replace("%SOURCE%", str(run_dir / "r5.json").replace("_", r"\_"))
    out.write_text(body)


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def main(results_dir: str = "results", out: str = "docs/tables") -> int:
    results_root = Path(results_dir)
    if not results_root.is_absolute():
        results_root = project_root() / results_root
    out_dir = Path(out)
    if not out_dir.is_absolute():
        out_dir = project_root() / out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    log_section(f"make_tables: results={results_root}  out={out_dir}")
    artifacts: list[dict] = []

    pairs = [
        ("r1", "t1_audit_decomposition.tex", write_t1_audit_decomposition),
        ("r2", "t2_redundancy_law.tex", write_t2_redundancy),
        ("r3", "t3_responsibility.tex", write_t3_responsibility),
        ("r4", "t4_risk_privacy.tex", write_t4_risk_privacy),
        ("r5", "t5_overhead.tex", write_t5_overhead),
    ]
    for rid, fname, fn in pairs:
        run = _latest_run(results_root, rid)
        if run is None:
            log_info(f"  skip {rid}: no run found")
            continue
        log_info(f"  {rid} run: {run.name}")
        target = out_dir / fname
        try:
            fn(run, target)
            artifacts.append({"name": fname, "source": str(run / f"{rid}.json")})
        except Exception as e:
            log_info(f"    ERROR writing {fname}: {e}")

    manifest = {"tables": artifacts, "out_dir": str(out_dir)}
    with (out_dir / "manifest.json").open("w") as fh:
        json.dump(manifest, fh, indent=2)
    log_info(f"Wrote {len(artifacts)} tables + manifest.json")
    return 0


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--results-dir", default="results")
    p.add_argument("--out", default="docs/tables")
    return p.parse_args()


if __name__ == "__main__":
    a = parse_args()
    sys.exit(main(results_dir=a.results_dir, out=a.out))
